-- ============================================================
-- Seed-Daten: DAV-Gewaesser Mitteldeutschland
-- Sachsen-Anhalt, Thueringen, Sachsen
-- Quelle: Offizielle Gewaesserverzeichnisse der Landesanglerverbande
-- ============================================================

-- Ensure name+bundesland is unique so ON CONFLICT works
alter table public.spots add constraint if not exists spots_name_bundesland_unique
  unique (name, bundesland);

-- Spots werden durch die Datenimport-Pipeline befuellt:
-- 1. data_pipeline/import_lav_pdf.py  (PDF → CSV)
-- 2. data_pipeline/geocoder.py        (CSV → geocodiertes CSV)
-- 3. data_pipeline/csv_to_seed.py     (CSV → SQL INSERT)
-- Generated by csv_to_seed.py from official DAV data
-- Source: spots_th_geo.csv
-- Total: 96 spots

INSERT INTO public.spots (name, latitude, longitude, bundesland, gewaesser_typ, fischarten, regelung, angelkarte_preis_tag, flaeche_ha, max_tiefe_m, strukturen, parkplatz, beschreibung) VALUES
('Speicher Dachwig', 51.072383, 10.850240, 'Thueringen', 'Talsperre',
 '["Aal", "Hecht", "Schleie", "Weißfisch", "Zander"]',
 'Bootsangeln erlaubt; Schonzeit Zander: 01.02. - 31.05.', NULL, 68.0, NULL,
 '[]', false,
 'Dieses idyllisch gelegene Gewässer befindet sich südlich der Verbindungsstraße Andisleben - Bad Langensalza, in der Flur zwischen Dachwig und Großfahner. Nach Passieren der Ortslage Dachwig zum Speicher links abbiegen. Das Angeln ist links von der Staumauer (ca. 700 m) und rechts von der Staumauer...')
ON CONFLICT (name, bundesland) DO NOTHING;

INSERT INTO public.spots (name, latitude, longitude, bundesland, gewaesser_typ, fischarten, regelung, angelkarte_preis_tag, flaeche_ha, max_tiefe_m, strukturen, parkplatz, beschreibung) VALUES
('Kiessee in der Königsecke – ehem. Teich II Kühnhausen', 51.034175, 10.971045, 'Thueringen', 'Teich',
 '[]',
 '', NULL, 10.54, NULL,
 '[]', false,
 'Dieses Gewässer ist von Kühnhausen in Richtung Mittelhausen zu erreichen. Ca. 600 m links hinter dem Bahndamm geht es in die Elxlebener Straße (neue Umgehungsstraße). Der PKW kann auf dem Parkplatz gegenüber dem Verwaltungsgebäude des Kieswerkes abgestellt werden. Die Uferseite am Campingplatz ist...')
ON CONFLICT (name, bundesland) DO NOTHING;

INSERT INTO public.spots (name, latitude, longitude, bundesland, gewaesser_typ, fischarten, regelung, angelkarte_preis_tag, flaeche_ha, max_tiefe_m, strukturen, parkplatz, beschreibung) VALUES
('Barschsee – Gemarkung Mittelhausen', 51.040508, 11.004852, 'Thueringen', 'See',
 '["Barsch", "Hecht", "Karpfen", "Schleie", "Weißfisch"]',
 '', NULL, 11.25, NULL,
 '[]', false,
 'Dieses Gewässer liegt östlich neben dem Reihersee (Denkmal). Guter Bestand an Karpfen, Schleie, Hecht, Barsch und Weißfischen vorhanden.')
ON CONFLICT (name, bundesland) DO NOTHING;

INSERT INTO public.spots (name, latitude, longitude, bundesland, gewaesser_typ, fischarten, regelung, angelkarte_preis_tag, flaeche_ha, max_tiefe_m, strukturen, parkplatz, beschreibung) VALUES
('Triftsee – Gemarkung Mittelhausen', 51.040508, 11.004852, 'Thueringen', 'See',
 '[]',
 '', NULL, 15.72, NULL,
 '[]', false,
 'Der Fischbestand befindet sich weiterhin im Aufbau. Aus diesem Grund ist im Jahr 2022 das Raubfischangeln ganzjährig verboten! Die Verwendung von Kunstködern, Drop Shot-Montagen, Köderfischen und Fetzenködern ist untersagt! Angeln auf Friedfisch ist erlaubt. Das Betreten der Inseln ist verboten.')
ON CONFLICT (name, bundesland) DO NOTHING;

INSERT INTO public.spots (name, latitude, longitude, bundesland, gewaesser_typ, fischarten, regelung, angelkarte_preis_tag, flaeche_ha, max_tiefe_m, strukturen, parkplatz, beschreibung) VALUES
('Sulzer See', 51.038059, 11.076603, 'Thueringen', 'See',
 '[]',
 'Bootsangeln erlaubt', NULL, 56.0, NULL,
 '[]', false,
 'Von Erfurt kommend über die Schwerborner Straße in Richtung Schwerborn oder über die Stotternheimer Chaussee aus Richtung Stotternheim zu erreichen. Alt bekanntes, fischartenreiches Gewässer am nördlichen Stadtrand.   Derzeit unterliegen die Angelbereiche den betrieblichen Erfordernissen und können...')
ON CONFLICT (name, bundesland) DO NOTHING;

INSERT INTO public.spots (name, latitude, longitude, bundesland, gewaesser_typ, fischarten, regelung, angelkarte_preis_tag, flaeche_ha, max_tiefe_m, strukturen, parkplatz, beschreibung) VALUES
('Klingesee Stotternheim', 51.056072, 11.042756, 'Thueringen', 'See',
 '["Hecht", "Karpfen", "Schleie", "Zander"]',
 'Bootsangeln erlaubt', NULL, 25.0, NULL,
 '[]', false,
 'Das Gewässer ist von Stotternheim Zentrum in Richtung Schwerborn unmittelbar nach Überqueren der Bahnlinie geradeaus zum Kieswerk Wagner zu erreichen. Es liegt auf der linken Seite der Plattenstraße. Zugang auch über den Feldweg hinter dem Bahnübergang rechts in Richtung Schwansee möglich. Ein...')
ON CONFLICT (name, bundesland) DO NOTHING;

INSERT INTO public.spots (name, latitude, longitude, bundesland, gewaesser_typ, fischarten, regelung, angelkarte_preis_tag, flaeche_ha, max_tiefe_m, strukturen, parkplatz, beschreibung) VALUES
('Stotternheimer Bad', 51.038059, 11.076603, 'Thueringen', 'See',
 '[]',
 '', NULL, 20.0, NULL,
 '[]', false,
 'Dieser saubere, idyllisch gelegene Kiessee mit gutem Fischbesatz befindet sich in der Nähe des Stotternheimer Bahnhofes in Richtung Schwerborn. Speziell für Angler wurde vom Eigentümer ein gesonderter Zugang zum Gewässer mit Parkplatz für PKW eingerichtet. Der Parkplatz ist wie folgt zu erreichen:...')
ON CONFLICT (name, bundesland) DO NOTHING;

INSERT INTO public.spots (name, latitude, longitude, bundesland, gewaesser_typ, fischarten, regelung, angelkarte_preis_tag, flaeche_ha, max_tiefe_m, strukturen, parkplatz, beschreibung) VALUES
('Nordstrand Erfurt', 50.977797, 11.028736, 'Thueringen', 'See',
 '["Aal", "Hecht", "Karpfen", "Schleie"]',
 'Bootsangeln erlaubt', NULL, 15.0, NULL,
 '[]', false,
 'Liegt am nördlichen Stadtrand von Erfurt und ist über die Eugen-Richter-Straße stadtauswärts, nach der Bahnunterführung rechts abbiegend in die Straße zum Nordstrand, zu erreichen. Ein sehr attraktives Altgewässer mit einem guten Bestand an kapitalen Hechten, Karpfen, Schleie und Aal. Dieses...')
ON CONFLICT (name, bundesland) DO NOTHING;

INSERT INTO public.spots (name, latitude, longitude, bundesland, gewaesser_typ, fischarten, regelung, angelkarte_preis_tag, flaeche_ha, max_tiefe_m, strukturen, parkplatz, beschreibung) VALUES
('Unterer Henneteich', 50.977797, 11.028736, 'Thueringen', 'Teich',
 '["Karpfen", "Schleie", "Zander"]',
 '', NULL, 0.6, NULL,
 '[]', false,
 'Ein interessantes Kleingewässer am Stadtrand von Erfurt mit gutem Karpfen- und Schleien- bestand. Zu erreichen über die Weimarische Straße, hinter Mc Donalds liegend. Beachte: Schonzeit für Zander ist vom 01.02. bis 31.05. In dieser Zeit ist das Angeln mit Kunstködern jeglicher Art, Drop...')
ON CONFLICT (name, bundesland) DO NOTHING;

INSERT INTO public.spots (name, latitude, longitude, bundesland, gewaesser_typ, fischarten, regelung, angelkarte_preis_tag, flaeche_ha, max_tiefe_m, strukturen, parkplatz, beschreibung) VALUES
('Speicher Vieselbach', 50.997494, 11.146044, 'Thueringen', 'Talsperre',
 '["Aal", "Hecht", "Karausche", "Karpfen", "Plötze", "Rotfeder", "Schleie", "Zander"]',
 '', NULL, 10.0, NULL,
 '[]', false,
 'Der Stau liegt zwischen den Ortschaften Mönchenholzhausen und Hochstedt und ist über die B7, Abfahrt Sömmerda (Möbelhaus Rieger), sowohl von Erfurt, als auch von Weimar gut erreichbar. Der gute Bestand an Karpfen, Zander, Schleie, Hecht, Aal, Plötze, Rotfeder und Karausche ist...')
ON CONFLICT (name, bundesland) DO NOTHING;

INSERT INTO public.spots (name, latitude, longitude, bundesland, gewaesser_typ, fischarten, regelung, angelkarte_preis_tag, flaeche_ha, max_tiefe_m, strukturen, parkplatz, beschreibung) VALUES
('Molschengrube Sömmerda', 51.199436, 11.068097, 'Thueringen', 'See',
 '["Aal", "Hecht", "Karpfen", "Schleie", "Weißfisch"]',
 '', NULL, 2.7, NULL,
 '[]', false,
 'Von Sömmerda aus in Richtung Straußfurt/Weißensee nach Durchfahrt Sömmerda hinter der Tankstelle und vor der Abzweigung nach Weißensee (Ampelanlage) nach rechts in den Gartenweg einbiegen. Gewässer liegt unmittelbar am Weg links. Von Straußfurt kommend hinter der Ampelanlage nach Weißensee...')
ON CONFLICT (name, bundesland) DO NOTHING;

INSERT INTO public.spots (name, latitude, longitude, bundesland, gewaesser_typ, fischarten, regelung, angelkarte_preis_tag, flaeche_ha, max_tiefe_m, strukturen, parkplatz, beschreibung) VALUES
('Kiessee Leubingen', 51.161826, 11.117487, 'Thueringen', 'See',
 '[]',
 '', NULL, 6.0, NULL,
 '[]', false,
 'Dieses attraktive Angelgewässer liegt in der Gemarkung Leubingen und ist aus Richtung Sömmerda über Wenigensömmern zu erreichen. Kurz vor der Ortschaft Leubingen links auf den ausgeschilderten Wirtschaftsweg des Kieswerkes abbiegen. Diesem noch ca. 600 m folgen und dann das Fahrzeug auf der rechten...')
ON CONFLICT (name, bundesland) DO NOTHING;

INSERT INTO public.spots (name, latitude, longitude, bundesland, gewaesser_typ, fischarten, regelung, angelkarte_preis_tag, flaeche_ha, max_tiefe_m, strukturen, parkplatz, beschreibung) VALUES
('Gera von Gemarkungsgrenze Elxleben/Walschleben bis Gemarkungsgrenze Andisleben/Ringleben', 50.876553, 12.083267, 'Thueringen', 'Fluss',
 '[]',
 '', NULL, 4.0, NULL,
 '[]', false,
 'Beginn der Gewässerstrecke 600 m flussaufwärts oberhalb der Brücke in Walschleben. Gewässerstrecke geht nahtlos in die Gemarkung Andisleben/Ringleben über. Bitte Ausschilderung beachten.')
ON CONFLICT (name, bundesland) DO NOTHING;

INSERT INTO public.spots (name, latitude, longitude, bundesland, gewaesser_typ, fischarten, regelung, angelkarte_preis_tag, flaeche_ha, max_tiefe_m, strukturen, parkplatz, beschreibung) VALUES
('Gera in der Gemarkung Andisleben/Ringleben bis Gemarkungsgrenze Ringleben/Gebesee', 51.082206, 10.926122, 'Thueringen', 'See',
 '[]',
 '', NULL, 3.1, NULL,
 '[]', false,
 'Ende Gewässerstrecke flussabwärts 150 m vor Ortseingangsschild Gebesee.')
ON CONFLICT (name, bundesland) DO NOTHING;

INSERT INTO public.spots (name, latitude, longitude, bundesland, gewaesser_typ, fischarten, regelung, angelkarte_preis_tag, flaeche_ha, max_tiefe_m, strukturen, parkplatz, beschreibung) VALUES
('Gera von Einmündung der Gera in die Unstrut bis zur Gemarkungsgrenze 150 m hinter dem Ortsausgangsschild Gebesee in', 50.876553, 12.083267, 'Thueringen', 'See',
 '["Blei", "Hasel", "Plötze", "Rotfeder"]',
 '', NULL, 3.5, NULL,
 '[]', false,
 'Richtung Ringleben • 2,2 km, ca. 3,5 ha Anfahrt über die Ortslage Gebesee – Sportplatz Richtung Ringleben bis zur Brücke oder über die B4 durch Gebesee in Richtung Straußfurt bis zur Brücke. Vor der Brücke rechts befindet sich eine kleine Abfahrt. Im Interesse der Fischhege besteht für die gesamte...')
ON CONFLICT (name, bundesland) DO NOTHING;

INSERT INTO public.spots (name, latitude, longitude, bundesland, gewaesser_typ, fischarten, regelung, angelkarte_preis_tag, flaeche_ha, max_tiefe_m, strukturen, parkplatz, beschreibung) VALUES
('Unstrut Gemarkung Herbsleben', 51.118958, 10.836199, 'Thueringen', 'Fluss',
 '[]',
 '', NULL, 5.0, NULL,
 '[]', false,
 'Von Straßenbrücke Ortsausgang linkes Ufer ca. 4 km und rechtes Ufer ca. 5,5 km stromabwärts bis Gemarkung Gebesee. Bitte Ausschilderung des SFV „Unstrut“ e.V. Herbsleben beachten.')
ON CONFLICT (name, bundesland) DO NOTHING;

INSERT INTO public.spots (name, latitude, longitude, bundesland, gewaesser_typ, fischarten, regelung, angelkarte_preis_tag, flaeche_ha, max_tiefe_m, strukturen, parkplatz, beschreibung) VALUES
('Unstrut in der Gemarkung Schwerstedt', 51.155247, 10.919421, 'Thueringen', 'Fluss',
 '[]',
 '', NULL, 4.2, NULL,
 '[]', false,
 'Hinter der Stadt Gebesee vor der Unstrutbrücke links abbiegen nach Schwerstedt bis zur Brücke. Ab Brücke ca. 3,5 km flussabwärts Angelstrecke. Oder über die B4 von Henschleben kommend ca. 1 km nach der Ortslage rechts über den Weg bis zum Kirchberg fahren. Hier die Fahrzeuge bitte abstellen. Das...')
ON CONFLICT (name, bundesland) DO NOTHING;

INSERT INTO public.spots (name, latitude, longitude, bundesland, gewaesser_typ, fischarten, regelung, angelkarte_preis_tag, flaeche_ha, max_tiefe_m, strukturen, parkplatz, beschreibung) VALUES
('Teildauerstau Straußfurt', 51.141955, 10.970429, 'Thueringen', 'Stausee',
 '[]',
 'Bootsangeln erlaubt', NULL, 206.0, NULL,
 '[]', false,
 'Zu erreichen ist das Rückhaltebecken über die B4, Ortslage Henschleben bzw. Straußfurt. Angelstrecken 1. Von Straußfurt kommend in Richtung Erfurt nach dem Bahnübergang Vehra nach ca. 300 m rechts abbiegen. Am Beginn des Hochwasserschutzdammes auf den Feldweg einfahren. Ab hier Angelstrecke ca. 800...')
ON CONFLICT (name, bundesland) DO NOTHING;

INSERT INTO public.spots (name, latitude, longitude, bundesland, gewaesser_typ, fischarten, regelung, angelkarte_preis_tag, flaeche_ha, max_tiefe_m, strukturen, parkplatz, beschreibung) VALUES
('Unstrut in der Gemarkung Vehra', 51.162432, 10.989534, 'Thueringen', 'Fluss',
 '[]',
 '', NULL, 4.5, NULL,
 '[]', false,
 'B4 bis Vehra bei Straußfurt. Beanglung vom Schöpfwerk Vehra am Ortsende hinter dem Sportplatz flussabwärts bis Einmündung der Gramme in die Unstrut. Beachte: Der Streckenabschnitt von der Eisenbahnbrücke, ca. 300 m flussabwärts, bis zum Schöpfwerk Vehra ist Schonstrecke. Angeln ist nicht erlaubt.')
ON CONFLICT (name, bundesland) DO NOTHING;

INSERT INTO public.spots (name, latitude, longitude, bundesland, gewaesser_typ, fischarten, regelung, angelkarte_preis_tag, flaeche_ha, max_tiefe_m, strukturen, parkplatz, beschreibung) VALUES
('Unstrut Gemarkung Wundersleben', 51.153622, 11.038854, 'Thueringen', 'Fluss',
 '[]',
 '', NULL, 5.4, NULL,
 '[]', false,
 'Dieser Gewässerabschnitt verläuft von Gemarkungsgrenze Straußfurt/Wundersleben bis beachten!  Gemarkungsgrenze Wundersleben/Schallenburg. Bitte Ausschilderung  Attraktives Angelgewässer mit einem artenreichen Fischbestand. Bitte beachten! - Für die Gewässer 37 und 38 gilt, dass Befahren des...')
ON CONFLICT (name, bundesland) DO NOTHING;

INSERT INTO public.spots (name, latitude, longitude, bundesland, gewaesser_typ, fischarten, regelung, angelkarte_preis_tag, flaeche_ha, max_tiefe_m, strukturen, parkplatz, beschreibung) VALUES
('Wasserspeicher Gänserieth', 51.140410, 11.000028, 'Thueringen', 'Talsperre',
 '[]',
 '', NULL, 0.15, NULL,
 '[]', false,
 'Zufahrt über Ortslage Werningshausen, hinter der Steinmetzfirma E. Spangenberg. Rechts (Triftstraße); nach ca. 500 m kleiner Dorfweiher mit Insel. Beachte: Vom 01.11. bis 01.03. Angelverbot.')
ON CONFLICT (name, bundesland) DO NOTHING;

INSERT INTO public.spots (name, latitude, longitude, bundesland, gewaesser_typ, fischarten, regelung, angelkarte_preis_tag, flaeche_ha, max_tiefe_m, strukturen, parkplatz, beschreibung) VALUES
('Ilm in Gemarkung Oßmannstedt bis Niederroßla/Zottelstedt', 51.017154, 11.426495, 'Thueringen', 'Fluss',
 '["Bachforelle"]',
 '', NULL, 11.7, NULL,
 '[]', false,
 '• 10,0 km, 11,7 ha Mischgewässer Ab 50 m oberhalb Brücke Gagarinstraße in Oßmannstedt bis Holzbrücke Oberroßla Mischgewässer Ab Ilmschlößchen Niederroßla bis Pachtgrenze Zottelstedt 1.  Laichschonstrecken “Hohe Leite“ Beginn Brücke Gagarinstraße in Oßmannstedt ca.1,0 km flussabwärts Länge: ca. 0,5...')
ON CONFLICT (name, bundesland) DO NOTHING;

INSERT INTO public.spots (name, latitude, longitude, bundesland, gewaesser_typ, fischarten, regelung, angelkarte_preis_tag, flaeche_ha, max_tiefe_m, strukturen, parkplatz, beschreibung) VALUES
('Neuer Kiessee Rudisleben', 50.801327, 10.955632, 'Thueringen', 'See',
 '[]',
 '', NULL, 6.0, NULL,
 '[]', false,
 'Die Kiesgrube von „Märker Kies GmbH“ in Arnstadt Rudisleben liegt links vom Hauptweg im Betriebsgelände. Das Gewässer ist über die Bundesstraße B4, von Erfurt kommend, zu erreichen. An der Kreuzung Rudisleben links in den Ort fahren, immer geradeaus, dann rechts in den Schulplatz abbiegen, bis...')
ON CONFLICT (name, bundesland) DO NOTHING;

INSERT INTO public.spots (name, latitude, longitude, bundesland, gewaesser_typ, fischarten, regelung, angelkarte_preis_tag, flaeche_ha, max_tiefe_m, strukturen, parkplatz, beschreibung) VALUES
('Speicher Kromsdorf und Nachstau', 51.001299, 11.370466, 'Thueringen', 'Talsperre',
 '["Aal", "Hecht", "Karausche", "Karpfen", "Plötze", "Rotfeder", "Schleie", "Zander"]',
 'Schonzeit Zander: 01.02. - 31.05.', NULL, 10.3, NULL,
 '[]', false,
 'Dieser Stau liegt in der Nähe von Weimar und ist über die B7 in Richtung Jena über das Gewerbegebiet Süßenborn zu erreichen. Kurz vor der Ortslage Kromsdorf rechts auf den Feldweg (Plattenweg) abbiegen und nach ca. 1 km erreichen Sie das Gewässer. Die Fahrzeuge sind am Anfang des Staudammes auf die...')
ON CONFLICT (name, bundesland) DO NOTHING;

INSERT INTO public.spots (name, latitude, longitude, bundesland, gewaesser_typ, fischarten, regelung, angelkarte_preis_tag, flaeche_ha, max_tiefe_m, strukturen, parkplatz, beschreibung) VALUES
('Naturbad Magdala', 50.906554, 11.446329, 'Thueringen', 'See',
 '["Aal", "Hecht", "Karpfen", "Schleie", "Weißfisch", "Zander"]',
 'Schonzeit Zander: 01.02. - 31.05.', NULL, 2.74, NULL,
 '[]', false,
 'Dieses Gewässer ist teilweise eingezäunt und liegt am Stadtrand von Magdala in Richtung Ottstedt (Ottstedter Straße) auf der linken Seite. Es wird deshalb auch Ottstedter Teich genannt. Kurz vor Beginn der Einzäunung des Gewässers kann man links abbiegen und das Gewässer über den Feldweg, welcher...')
ON CONFLICT (name, bundesland) DO NOTHING;

INSERT INTO public.spots (name, latitude, longitude, bundesland, gewaesser_typ, fischarten, regelung, angelkarte_preis_tag, flaeche_ha, max_tiefe_m, strukturen, parkplatz, beschreibung) VALUES
('Talsperre Loßnitz', 50.860475, 11.341823, 'Thueringen', 'Talsperre',
 '["Barsch", "Karpfen", "Plötze", "Schleie", "Zander"]',
 'Schonzeit Zander: 01.02. - 31.05.', NULL, 3.5, NULL,
 '[]', false,
 'Das Gewässer ist von der A4 und Magdala kommend in Richtung Blankenhain über Tromlitz und Söllnitz zu erreichen und liegt kurz hinter Loßnitz auf der linken Seite. Von Blankenhain kommend über Rottdorf liegt es rechts. Ein idyllisch gelegenes Gewässer mit einem guten Fischbestand (Karpfen, Schleie,...')
ON CONFLICT (name, bundesland) DO NOTHING;

INSERT INTO public.spots (name, latitude, longitude, bundesland, gewaesser_typ, fischarten, regelung, angelkarte_preis_tag, flaeche_ha, max_tiefe_m, strukturen, parkplatz, beschreibung) VALUES
('Lohteich Apolda', 51.022788, 11.512974, 'Thueringen', 'Teich',
 '[]',
 '', NULL, 0.7, NULL,
 '[]', false,
 NULL)
ON CONFLICT (name, bundesland) DO NOTHING;

INSERT INTO public.spots (name, latitude, longitude, bundesland, gewaesser_typ, fischarten, regelung, angelkarte_preis_tag, flaeche_ha, max_tiefe_m, strukturen, parkplatz, beschreibung) VALUES
('Friedensteich Apolda', 51.022788, 11.512974, 'Thueringen', 'Teich',
 '["Aal", "Barsch", "Giebel", "Karpfen", "Plötze", "Rotfeder", "Zander"]',
 'Schonzeit Zander: 01.02. - 31.05.', NULL, 1.5, NULL,
 '[]', false,
 'Diese beiden attraktiven Kleingewässer liegen in Apolda an der Herressener Promenade. Durch gezielte Hege- und Besatzmaßnahmen hat sich nach den erfolgten Sanierungsmaßnahmen wieder ein guter Fischbestand entwickelt. Beachte! - Gefangene Goldfische und Giebel müssen aus hegerischen Gründen aus...')
ON CONFLICT (name, bundesland) DO NOTHING;

INSERT INTO public.spots (name, latitude, longitude, bundesland, gewaesser_typ, fischarten, regelung, angelkarte_preis_tag, flaeche_ha, max_tiefe_m, strukturen, parkplatz, beschreibung) VALUES
('Pfaffenteich', 51.366604, 10.866842, 'Thueringen', 'Teich',
 '["Aal", "Hecht", "Karpfen", "Schleie", "Weißfisch"]',
 '', NULL, 1.77, NULL,
 '[]', false,
 'Lage: Nordöstlich im Stadtwald von Sondershausen. Zufahrt über Brückental (Krankenhaus, Hauptfriedhof) ca. 5 km durch den Stadtwald immer gerade durch (nicht abbiegen). Fischbestand: Karpfen, Schleie, Weißfisch, Aal, Hecht')
ON CONFLICT (name, bundesland) DO NOTHING;

INSERT INTO public.spots (name, latitude, longitude, bundesland, gewaesser_typ, fischarten, regelung, angelkarte_preis_tag, flaeche_ha, max_tiefe_m, strukturen, parkplatz, beschreibung) VALUES
('Hammateich', 51.366604, 10.866842, 'Thueringen', 'Teich',
 '[]',
 '', NULL, 58.0, NULL,
 '[]', false,
 'Lage: Der Teich liegt in der Hammatalstraße. Zu erreichen über Kreisel Nordhäuser Straße in Sondershausen, die 3. Abfahrt stadteinwärts. Gegenüber dem Teich befindet sich die Ausflugsgaststätte „Stille Liebe“. Bitte beachten! - Das Gewässer muss saniert werden und hat aktuell kein Wasser. Angeln...')
ON CONFLICT (name, bundesland) DO NOTHING;

INSERT INTO public.spots (name, latitude, longitude, bundesland, gewaesser_typ, fischarten, regelung, angelkarte_preis_tag, flaeche_ha, max_tiefe_m, strukturen, parkplatz, beschreibung) VALUES
('Großer Parkteich Sondershausen', 51.366604, 10.866842, 'Thueringen', 'Teich',
 '["Barsch", "Giebel", "Karpfen", "Plötze", "Rotfeder", "Schleie"]',
 '', NULL, 1.01, NULL,
 '[]', false,
 'Beachte: Der Fischbestand befindet sich derzeit im Aufbau. Angeln auf Raubfische verboten! Dieses Gewässer liegt im Stadtpark zwischen Hospitalstraße und Marktplatz im Zentrum von Sondershausen. Günstiges Parken ist auf dem kostenlosen Außenparkplatz vom Kaufand möglich. Von da aus ist der Teich in...')
ON CONFLICT (name, bundesland) DO NOTHING;

INSERT INTO public.spots (name, latitude, longitude, bundesland, gewaesser_typ, fischarten, regelung, angelkarte_preis_tag, flaeche_ha, max_tiefe_m, strukturen, parkplatz, beschreibung) VALUES
('Baderteich Ronneburg', 50.863052, 12.180907, 'Thueringen', 'Teich',
 '["Aal", "Giebel", "Hecht", "Karpfen", "Schleie"]',
 '', NULL, 2.5, NULL,
 '[]', false,
 'Der Baderteich befindet sich im Zentrum von Ronneburg, direkt unter dem Schloss. Trotz seiner zentralen Lage ist es angenehm ruhig. Der Teich hat eine Größe von ca. 2,5 ha und eine Tiefe von maximal 3 m. Die Hauptfischarten sind Karpfen, Schleie, Hecht und Aal. Für Giebel besteht eine...')
ON CONFLICT (name, bundesland) DO NOTHING;

INSERT INTO public.spots (name, latitude, longitude, bundesland, gewaesser_typ, fischarten, regelung, angelkarte_preis_tag, flaeche_ha, max_tiefe_m, strukturen, parkplatz, beschreibung) VALUES
('Parkteich Farnroda', 50.974713, 10.319356, 'Thueringen', 'Teich',
 '["Blei", "Hecht", "Karpfen", "Plötze", "Rotfeder", "Schleie"]',
 '', NULL, 0.5, NULL,
 '[]', false,
 'Dieses interessante Gewässer ist von Eisenach oder Erfurt kommend über die L3007 (ehemals B7) und der Ortsmitte von Wutha - Farnroda erreichbar. In Wutha an der Ampelkreuzung in Richtung Ruhla fahren. An der zweiten Ampel im Ortsteil Farnroda nach rechts und nach 10 m wieder rechts in den...')
ON CONFLICT (name, bundesland) DO NOTHING;

INSERT INTO public.spots (name, latitude, longitude, bundesland, gewaesser_typ, fischarten, regelung, angelkarte_preis_tag, flaeche_ha, max_tiefe_m, strukturen, parkplatz, beschreibung) VALUES
('Wipper', 51.401213, 10.795613, 'Thueringen', 'Fluss',
 '["Aal", "Bachforelle", "Barsch", "Döbel", "Giebel", "Gründling", "Hasel", "Hecht", "Karpfen", "Plötze"]',
 '', NULL, 0.0, NULL,
 '[]', false,
 'Beginn: Gemarkungsgrenze Sondershausen Großfurra/Sondershausen Verlauf: Sondershausen, Berka, Hachelbich, Göllingen, Seega, Günserode Ende: Gemarkungsgrenze Günserode/Bilzingsleben (SÖM) Hauptfischarten: Hecht, Aal, Barsch, Karpfen, Plötze, Giebel, Hasel, Gründling, Döbel, Bachforelle')
ON CONFLICT (name, bundesland) DO NOTHING;

INSERT INTO public.spots (name, latitude, longitude, bundesland, gewaesser_typ, fischarten, regelung, angelkarte_preis_tag, flaeche_ha, max_tiefe_m, strukturen, parkplatz, beschreibung) VALUES
('Unstrut', 51.234721, 11.112729, 'Thueringen', 'Fluss',
 '["Aal", "Barsch", "Blei", "Döbel", "Hasel", "Hecht", "Karpfen", "Plötze", "Ukelei", "Zander"]',
 '', NULL, 62.0, NULL,
 '[]', false,
 'Beginn: Gemarkungsgrenze Sachsenburg - Oldisleben Verlauf: Oldisleben, Heldrungen, Bretleben, Schönfeld, Artern, Ritteburg, Kalbsrieth, Schönewerda, Bottendorf, Roßleben Ende: Landes und Kreisgrenze Thüringen / Sachsen Anhalt bei Roßleben Hauptfischarten: Hecht, Barsch, Döbel, Ukelei, Hasel,...')
ON CONFLICT (name, bundesland) DO NOTHING;

INSERT INTO public.spots (name, latitude, longitude, bundesland, gewaesser_typ, fischarten, regelung, angelkarte_preis_tag, flaeche_ha, max_tiefe_m, strukturen, parkplatz, beschreibung) VALUES
('Helme', 51.448703, 10.945639, 'Thueringen', 'Fluss',
 '["Aal", "Bachforelle", "Barbe", "Barsch", "Döbel", "Gründling", "Hasel", "Hecht", "Karpfen", "Plötze", "Schleie", "Ukelei"]',
 '', NULL, 7.0, NULL,
 '[]', false,
 'Beginn: Gemarkungsgrenze Mönchpfiffel/Allstedt (Thüringen/Sachsen Anhalt) Verlauf: Mönchpfiffel-Nicolausrieth, Heygendorf, Kalbsrieth Ende: Mündung in die Unstrut bei Kalbsrieth. Hauptfischarten: Hasel, Döbel, Plötze, Barsch, Bachforelle, Ukelei, Aal, Hecht, Schleie, Karpfen, Gründling, Barbe')
ON CONFLICT (name, bundesland) DO NOTHING;

INSERT INTO public.spots (name, latitude, longitude, bundesland, gewaesser_typ, fischarten, regelung, angelkarte_preis_tag, flaeche_ha, max_tiefe_m, strukturen, parkplatz, beschreibung) VALUES
('Stau Podelsatz', 50.894318, 11.691368, 'Thueringen', 'Stausee',
 '["Aal", "Barsch", "Hecht", "Karpfen", "Plötze", "Rotfeder", "Schleie", "Zander"]',
 '', NULL, 6.99, NULL,
 '[]', false,
 'Anfahrt: Über die L 1077 vor der Ortslage Gernewitz nach links in Richtung Schlöben abbiegen und nach der Unterquerung der Autobahn in den Feldweg rechts abbiegen. Besonderheiten: Das Angeln im Vogelschutzgebiet im Einlaufbereich am eingezäunten Nordufer ist nicht erlaubt. Das Abstellen der...')
ON CONFLICT (name, bundesland) DO NOTHING;

INSERT INTO public.spots (name, latitude, longitude, bundesland, gewaesser_typ, fischarten, regelung, angelkarte_preis_tag, flaeche_ha, max_tiefe_m, strukturen, parkplatz, beschreibung) VALUES
('Stau Ruttersdorf', 50.858267, 11.726364, 'Thueringen', 'Stausee',
 '["Aal", "Barsch", "Hecht", "Plötze", "Rotfeder", "Schleie"]',
 '', NULL, 3.8, NULL,
 '[]', false,
 'Anfahrt: Über die L1077, in Stadtroda in Richtung Bahnhof und weiter in Richtung Ruttersdorf, 1 km vor Ruttersdorf in Richtung Lotschen links abbiegen. Besonderheiten: Angeln in Schilfzonen sowie das Befahren des Mönchgeländes und der Wiese südlich vom Gewässer sind verboten. Fischarten: Aal,...')
ON CONFLICT (name, bundesland) DO NOTHING;

INSERT INTO public.spots (name, latitude, longitude, bundesland, gewaesser_typ, fischarten, regelung, angelkarte_preis_tag, flaeche_ha, max_tiefe_m, strukturen, parkplatz, beschreibung) VALUES
('Saale', 50.904125, 11.732191, 'Thueringen', 'Fluss',
 '[]',
 '', NULL, 65.5, NULL,
 '[]', false,
 'Anfahrt: Über B 88 und öffentliche Wege der Stadt Jena. Angelbereich: Stadtgebiet Jena, von 600 m oberhalb der Saalebrücke Maua bis zum Erdengraben in der Gemarkung Neuengönna/Dorndorf. Dieser kr euzt die B88 in einer S-Kurve bei Neuengönna. Schongebiete im Bereich Wehr Stadtrodaer Straße und...')
ON CONFLICT (name, bundesland) DO NOTHING;

INSERT INTO public.spots (name, latitude, longitude, bundesland, gewaesser_typ, fischarten, regelung, angelkarte_preis_tag, flaeche_ha, max_tiefe_m, strukturen, parkplatz, beschreibung) VALUES
('Speicher Römhild', 50.392758, 10.567828, 'Thueringen', 'Talsperre',
 '["Zander"]',
 'Schonzeit Zander: 01.02. - 31.05.', NULL, 5.2, NULL,
 '[]', false,
 'Der Speicher, ein interessantes Angelgewässer mit einem guten Fischbestand, befindet sich am westlichen Fuß des kleinen Gleichbergs. Die Anfahrt erfolgt über die Ortsverbindungsstraße Römhild – Hildburghausen. Ca. 1 km nach Römhild nach links vor der Siloanlage auf den Feldweg abbiegen. Das Parken...')
ON CONFLICT (name, bundesland) DO NOTHING;

INSERT INTO public.spots (name, latitude, longitude, bundesland, gewaesser_typ, fischarten, regelung, angelkarte_preis_tag, flaeche_ha, max_tiefe_m, strukturen, parkplatz, beschreibung) VALUES
('Speicher Roth', 50.426623, 10.730011, 'Thueringen', 'Talsperre',
 '["Aal", "Hecht", "Karpfen", "Plötze", "Rotfeder", "Zander"]',
 'Schonzeit Zander: 01.02. - 31.05.', NULL, 4.0, NULL,
 '[]', false,
 'Der Speicher liegt im Gleichberggebiet zwischen den Ortschaften Römhild - Zeilfeld -Roth Die Anfahrt erfolgt über die Ortsverbindungsstraße Römhild - Zeilfeld. Ca. 750 m nach dem Waldhaus in Richtung Hildburghausen rechts auf den Waldweg abbiegen. Dann ca. 750 m in einem Kreisverkehr das Auto...')
ON CONFLICT (name, bundesland) DO NOTHING;

INSERT INTO public.spots (name, latitude, longitude, bundesland, gewaesser_typ, fischarten, regelung, angelkarte_preis_tag, flaeche_ha, max_tiefe_m, strukturen, parkplatz, beschreibung) VALUES
('Talsperre Wechmar', 50.891604, 10.777913, 'Thueringen', 'Talsperre',
 '["Aal", "Bachforelle", "Barsch", "Gründling", "Hecht", "Karpfen", "Plötze", "Rotfeder", "Schleie", "Zander"]',
 '', NULL, 39.0, NULL,
 '[]', false,
 'Sehr idyllisch gelegenes Gewässer im Osten des Gemeindegebietes von Wechmar im Landkreis Gotha. Anfahrt: L 1045 in Richtung Wechmar fahren. Unmittelbar vor dem Ortseingang rechts auf den Wirtschaftsweg abbiegen und diesen bis zur Talsperre folgen. Alternativ: Von Wandersleben nach Wechmar kommend,...')
ON CONFLICT (name, bundesland) DO NOTHING;

INSERT INTO public.spots (name, latitude, longitude, bundesland, gewaesser_typ, fischarten, regelung, angelkarte_preis_tag, flaeche_ha, max_tiefe_m, strukturen, parkplatz, beschreibung) VALUES
('Neu. – Luhneteiche', 51.258813, 10.311029, 'Thueringen', 'Teich',
 '["Hecht", "Karpfen", "Rotfeder", "Schleie"]',
 '', NULL, 0.6, NULL,
 '[]', false,
 'Diese Teiche sind durch einen Naturdamm geteilt und liegen am Rande eines ruhigen Waldgebiets. Anfahrt: Diese Gewässer sind von Büttstedt (PLZ 37359) in Richtung Küllstedt (PLZ 37359) über die Bahnhofstraße fahrend zu erreichen. Dazu fahren Sie ca. 500 m nach Ortsausgang Büttstedt rechts auf einen...')
ON CONFLICT (name, bundesland) DO NOTHING;

INSERT INTO public.spots (name, latitude, longitude, bundesland, gewaesser_typ, fischarten, regelung, angelkarte_preis_tag, flaeche_ha, max_tiefe_m, strukturen, parkplatz, beschreibung) VALUES
('Neu.- Seeloch Gernrode', 51.354618, 10.476223, 'Thueringen', 'See',
 '["Bachforelle", "Hecht", "Karpfen", "Rotfeder", "Schleie"]',
 '', NULL, 0.25, NULL,
 '[]', false,
 'Bei diesem Gewässer handelt es sich um eine alte Torflinse. Anfahrt: Von der A 38 kommend, Abfahrt Breitenworbis nehmen und in Richtung Deuna (L1015) fahren. Nach ca. 400 m rechts abbiegen Richtung Gernrode (L1014), dort nach ca. 700 m rechts und nach weiteren 250 m vor der Brückenunterführung...')
ON CONFLICT (name, bundesland) DO NOTHING;

INSERT INTO public.spots (name, latitude, longitude, bundesland, gewaesser_typ, fischarten, regelung, angelkarte_preis_tag, flaeche_ha, max_tiefe_m, strukturen, parkplatz, beschreibung) VALUES
('Apfelstädt', 50.866360, 10.736093, 'Thueringen', 'Fluss',
 '["Äsche"]',
 '', NULL, 17.0, NULL,
 '[]', false,
 'Beginn von Flurgrenze Gemarkungsgrenze Wechmar/Wandersleben, Einmündung Schmallgraben bis Mündung Gera bei Mariental. Einst ein attraktives Salmonidenge- wässer im Nahbereich von Erfurt. Auf Grund eines fragwürdigen Wassermanagements des Freistaates Thüringen und zu geringer Niederschläge in den...')
ON CONFLICT (name, bundesland) DO NOTHING;

INSERT INTO public.spots (name, latitude, longitude, bundesland, gewaesser_typ, fischarten, regelung, angelkarte_preis_tag, flaeche_ha, max_tiefe_m, strukturen, parkplatz, beschreibung) VALUES
('Gera, Gemarkung Plaue, Dosdorf und Siegelbach', 50.777649, 10.898091, 'Thueringen', 'Fluss',
 '[]',
 '', NULL, 4.5, NULL,
 '[]', false,
 'Die Angelstrecke beginnt am Zusammenlauf der Wilden und Zahmen Gera, an der Uferstraße in Plaue. Erreichbar über B4 an der Brücke gegenüber Einkaufszentrum, in Dosdorf über die Straße zur Rindermastanlage und in Siegelbach an der Straßenbrücke am Ortseingang.')
ON CONFLICT (name, bundesland) DO NOTHING;

INSERT INTO public.spots (name, latitude, longitude, bundesland, gewaesser_typ, fischarten, regelung, angelkarte_preis_tag, flaeche_ha, max_tiefe_m, strukturen, parkplatz, beschreibung) VALUES
('Gera, Gemarkung Arnstadt', 50.801327, 10.955632, 'Thueringen', 'Fluss',
 '["Bachforelle"]',
 '', NULL, 4.32, NULL,
 '[]', false,
 'Die Angelstrecke schließt sich nahtlos an die Gewässerstrecke Nr. 131 an. Sie endet an der Gemarkungsgrenze Arnstadt - Rudisleben. Im gesamten Stadtgebiet von Arnstadt ist sie gut zugänglich. Beide Gewässerstrecken der Gera (Nr. 131 und 132) sind attraktive Salmonidengewässer mit einem guten...')
ON CONFLICT (name, bundesland) DO NOTHING;

INSERT INTO public.spots (name, latitude, longitude, bundesland, gewaesser_typ, fischarten, regelung, angelkarte_preis_tag, flaeche_ha, max_tiefe_m, strukturen, parkplatz, beschreibung) VALUES
('Gera Gemarkung Molsdorf', 50.904433, 10.960882, 'Thueringen', 'Fluss',
 '[]',
 '', NULL, 8.4, NULL,
 '[]', false,
 'Von der Gemarkung Eischleben (ca. 1,5 km von der Autobahnbrücke Molsdorf in Richtung Eischleben) flussabwärts bis Mariental, kurz hinter der Ei nmündung der Apfelstädt in die Gera.')
ON CONFLICT (name, bundesland) DO NOTHING;

INSERT INTO public.spots (name, latitude, longitude, bundesland, gewaesser_typ, fischarten, regelung, angelkarte_preis_tag, flaeche_ha, max_tiefe_m, strukturen, parkplatz, beschreibung) VALUES
('Gera/Flutgraben Gemarkung Erfurt einschließl. der innerstädtischen Gewässer: Bergstrom, Walkstrom, Breitstrom u. schmale Gera', 50.977797, 11.028736, 'Thueringen', 'Kanal',
 '[]',
 '', NULL, 24.0, NULL,
 '[]', false,
 'km, ca. 24 ha Von Papierwehr Erfurt (Dreienbrunnenbad) flussabwärts bis zur Brücke Straße der Nationen. Flugangelstrecken: 1. Die innerstädtischen Gewässer Bergstrom, Walkstrom, Breitstrom und schmale Gera 2. Gera/Flutgraben von Papierwehr bis Wehr Talbrücke In diesen Gewässern/Gewässerabschnitten...')
ON CONFLICT (name, bundesland) DO NOTHING;

INSERT INTO public.spots (name, latitude, longitude, bundesland, gewaesser_typ, fischarten, regelung, angelkarte_preis_tag, flaeche_ha, max_tiefe_m, strukturen, parkplatz, beschreibung) VALUES
('Linderbach von Gemarkung Linderbach bis Einmündung', 50.978980, 11.100599, 'Thueringen', 'Fluss',
 '[]',
 '', NULL, 2.8, NULL,
 '[]', false,
 'in die Gramme bei Kleinmölsen • 7 km, ca. 2,8 ha')
ON CONFLICT (name, bundesland) DO NOTHING;

INSERT INTO public.spots (name, latitude, longitude, bundesland, gewaesser_typ, fischarten, regelung, angelkarte_preis_tag, flaeche_ha, max_tiefe_m, strukturen, parkplatz, beschreibung) VALUES
('Ilm Gemarkung Kranichfeld/Bad Berka', 50.852652, 11.199890, 'Thueringen', 'See',
 '[]',
 '', NULL, 4.5, NULL,
 '[]', false,
 'Von Flurgrenze Kranichfeld (Einlauf Haubach oberhalb Tannroda) flussabwärts bis Flurgrenze Bad Berka unterhalb Wehr München. Ortslage Dienstedt (ca. 100 m unterhalb Klunkermühle bis Einlauf Mettbach Ortsausgang Dienstedt)')
ON CONFLICT (name, bundesland) DO NOTHING;

INSERT INTO public.spots (name, latitude, longitude, bundesland, gewaesser_typ, fischarten, regelung, angelkarte_preis_tag, flaeche_ha, max_tiefe_m, strukturen, parkplatz, beschreibung) VALUES
('Ilm von Gemarkung Weimar, 400 m oberhalb des Ortsschildes', 50.979330, 11.329792, 'Thueringen', 'Fluss',
 '["Äsche"]',
 '', NULL, 12.0, NULL,
 '[]', false,
 'Weimar an der Taubacher Straße der oberen Pachtgrenze flussabwärts in Richtung Weimar, Tiefurt, Kromsdorf bis 2. Brücke Denstedt • 12,7 km, ca. 12 ha Die gesamte Pachtstrecke darf mit der Flugangel beangelt werden. Spinnangeln nur in den nachfolgend genannten Gewässerabschnitten erlaubt: - von...')
ON CONFLICT (name, bundesland) DO NOTHING;

INSERT INTO public.spots (name, latitude, longitude, bundesland, gewaesser_typ, fischarten, regelung, angelkarte_preis_tag, flaeche_ha, max_tiefe_m, strukturen, parkplatz, beschreibung) VALUES
('Ilm Gemarkung Denstedt', 51.017154, 11.426495, 'Thueringen', 'Fluss',
 '["Äsche"]',
 '', NULL, 4.6, NULL,
 '[]', false,
 'Beginn 2. Brücke Denstedt in Richtung Linkershof bis Brücke Ulrichshalben, Richtung Oßmannstedt. Guter Bestand an Äschen. Flugangelstrecke ab Brücke Denstedt bis ehemals „offener Stall“ Oßmannstedt. Spinn- und Flugangelstrecke ab ehemals „offener Stall“ Oßmannstedt bis 50 m oberhalb der Brücke...')
ON CONFLICT (name, bundesland) DO NOTHING;

INSERT INTO public.spots (name, latitude, longitude, bundesland, gewaesser_typ, fischarten, regelung, angelkarte_preis_tag, flaeche_ha, max_tiefe_m, strukturen, parkplatz, beschreibung) VALUES
('Ilm Gemarkung Niederroßla/Zottelstedt', 51.037040, 11.475478, 'Thueringen', 'Fluss',
 '["Bachforelle"]',
 '', NULL, 0.9, NULL,
 '[]', false,
 'Spinn- und Flugangelstrecke 500 m oberhalb vom Wehr Zottelstedt Sportplatz in Richtung Niederroßla flussaufwärts. Zufahrt über die B87, BP Tankstelle Apolda, Abzweig Zottelstedt. Guter Bestand an Bachforellen. Wichtig: Bitte die Ausschilderung beachten. Zugang zum Gewässer über das...')
ON CONFLICT (name, bundesland) DO NOTHING;

INSERT INTO public.spots (name, latitude, longitude, bundesland, gewaesser_typ, fischarten, regelung, angelkarte_preis_tag, flaeche_ha, max_tiefe_m, strukturen, parkplatz, beschreibung) VALUES
('Schnauder, Gemarkung Meuselwitz', 51.047500, 12.297500, 'Thueringen', 'Fluss',
 '["Bachforelle", "Barsch", "Döbel", "Gründling", "Hasel", "Hecht", "Plötze"]',
 '', NULL, 3.05, NULL,
 '[]', false,
 'Die Spinn- und Flugangelstrecke beginnt aus Richtung Zeitz kommend ca. 1 km nach der Ausfahrt Oelsen der B180 (rechts abbiegend in Kopfsteinpflasterweg), geht durch das gesamte Stadtgebiet von Meuselwitz und endet ca. 800 m nach der Schnauderbrücke Heukendorfer Weg im Stadtteil...')
ON CONFLICT (name, bundesland) DO NOTHING;

INSERT INTO public.spots (name, latitude, longitude, bundesland, gewaesser_typ, fischarten, regelung, angelkarte_preis_tag, flaeche_ha, max_tiefe_m, strukturen, parkplatz, beschreibung) VALUES
('Hörsel, Gemarkung Eisenach Wutha bis Straßenbrücke Schönau', 50.974713, 10.319356, 'Thueringen', 'Fluss',
 '["Bachforelle"]',
 '', NULL, 4.0, NULL,
 '[]', false,
 'Ein attraktives Fließgewässer mit einem guten Bestand an Bachforellen. Die Gewässerstrecke beginnt in Höhe des Kreisverkehrs zur Autobahn A4 vor Wutha und endet an der Straßenbrücke Schönau. Beachte: Der in Wutha einmündende Bach „Erbstrom“ ist ein Aufzuchtgewässer und darf nicht beangelt werden.')
ON CONFLICT (name, bundesland) DO NOTHING;

INSERT INTO public.spots (name, latitude, longitude, bundesland, gewaesser_typ, fischarten, regelung, angelkarte_preis_tag, flaeche_ha, max_tiefe_m, strukturen, parkplatz, beschreibung) VALUES
('Stau Fuchsgrund', 50.974713, 10.319356, 'Thueringen', 'Stausee',
 '["Bachforelle"]',
 '', NULL, 0.8, NULL,
 '[]', false,
 'Der Fuchsgrund, welcher durch zwei Waldbäche gespeist wird, beherbergt auf Grund seines sauberen, kühlen Wassers vor allem Bachforellen. Bitte beachten: Das Angeln ist erst ab 1. Mai erlaubt! Zu erreichen von Eisenach oder Erfurt kommend über die L3007 (ehemals B7) bis Ortsmitte Wutha - Farnroda....')
ON CONFLICT (name, bundesland) DO NOTHING;

INSERT INTO public.spots (name, latitude, longitude, bundesland, gewaesser_typ, fischarten, regelung, angelkarte_preis_tag, flaeche_ha, max_tiefe_m, strukturen, parkplatz, beschreibung) VALUES
('Neu. - Unstrut', 51.234721, 11.112729, 'Thueringen', 'Fluss',
 '["Bachforelle"]',
 '', NULL, NULL, NULL,
 '[]', false,
 'Dieses Fließgewässer zeichnet sich durch viele kleine Kolke aus. In dem Gewässerabschnitt befinden sich auch mehrere Wehre. Bitte die Ausschilderung beachten! Wichtiger Hinweis! - Es handelt sich um ein Fließgewässer der EU-Kategorie 1. Vor Beginn des Angelns müssen sämtliche Gerätschaften, Stiefel...')
ON CONFLICT (name, bundesland) DO NOTHING;
