"""
Convert geocoded fishing spot CSV to SQL INSERT statements for seed.sql.

Reads CSV output from geocoder.py and generates PostgreSQL INSERT statements
matching the spots table schema.

Usage:
    python csv_to_seed.py spots_geocoded.csv --out seed.sql
"""

from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path


def escape_sql(value: str) -> str:
    """Escape single quotes for SQL string literals."""
    return value.replace("'", "''")


def csv_to_sql(input_path: Path, output_path: Path, bundesland: str = '') -> None:
    """Convert geocoded CSV to SQL INSERT statements."""
    with open(input_path, newline='', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        rows = list(reader)

    if not rows:
        print("No rows found in CSV.")
        return

    lines: list[str] = []
    lines.append("-- Generated by csv_to_seed.py from official DAV data")
    lines.append(f"-- Source: {input_path.name}")
    lines.append(f"-- Total: {len(rows)} spots")
    lines.append("")

    skipped = 0
    inserted = 0

    for row in rows:
        lat = row.get('latitude', '').strip()
        lon = row.get('longitude', '').strip()

        # Skip rows without coordinates
        if not lat or not lon:
            skipped += 1
            continue

        name = escape_sql(row.get('name', '').strip())
        bl = escape_sql(bundesland or row.get('bundesland', '').strip())
        typ = escape_sql(row.get('gewaesser_typ', 'See').strip())

        # Build fischarten JSON array
        fischarten_raw = row.get('fischarten', '').strip()
        if fischarten_raw:
            species = [s.strip() for s in fischarten_raw.split(',') if s.strip()]
            fischarten_json = json.dumps(species, ensure_ascii=False)
        else:
            fischarten_json = '[]'

        regelung = escape_sql(row.get('regelung', '').strip())

        # Nullable numeric fields
        flaeche = row.get('flaeche_ha', '').strip()
        flaeche_sql = flaeche if flaeche else 'NULL'

        # max_tiefe_m — not available from PDF sources
        tiefe_sql = 'NULL'

        # strukturen — not available from PDF sources
        strukturen_sql = "'[]'"

        parkplatz = 'false'
        beschreibung_raw = row.get('beschreibung', '').strip()
        beschreibung_sql = f"'{escape_sql(beschreibung_raw)}'" if beschreibung_raw else 'NULL'

        # angelkarte_preis_tag — not reliably available from PDFs
        preis_sql = 'NULL'

        lines.append(
            f"INSERT INTO public.spots "
            f"(name, latitude, longitude, bundesland, gewaesser_typ, "
            f"fischarten, regelung, angelkarte_preis_tag, flaeche_ha, "
            f"max_tiefe_m, strukturen, parkplatz, beschreibung) VALUES"
        )
        lines.append(
            f"('{name}', {lat}, {lon}, '{bl}', '{typ}',\n"
            f" '{fischarten_json}',\n"
            f" '{regelung}', {preis_sql}, {flaeche_sql}, {tiefe_sql},\n"
            f" {strukturen_sql}, {parkplatz},\n"
            f" {beschreibung_sql})\n"
            f"ON CONFLICT (name, bundesland) DO NOTHING;\n"
        )
        inserted += 1

    with open(output_path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))

    print(f"Generated {inserted} INSERT statements to {output_path}")
    if skipped:
        print(f"Skipped {skipped} rows without coordinates")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Convert geocoded CSV to SQL INSERT statements"
    )
    parser.add_argument("csv_file", type=Path, help="Input geocoded CSV")
    parser.add_argument(
        "--out", type=Path, default=Path("seed_generated.sql"),
        help="Output SQL file",
    )
    parser.add_argument(
        "--bundesland", default="",
        help="Override bundesland for all rows",
    )
    args = parser.parse_args()

    csv_to_sql(args.csv_file, args.out, args.bundesland)


if __name__ == "__main__":
    main()
